@startuml Use_Cases
skinparam ArrowColor #777777
skinparam BackgroundColor #ffffff

actor User
rectangle "PickUp-Delivery System" {
  usecase "Upload XMLs & Compute TSP" as UC1
  usecase "Select Existing Files & Compute TSP" as UC2
  usecase "List Plan Names" as UC3
  usecase "List Request Names" as UC4
  usecase "View Plan XML" as UC5
  usecase "View Request XML" as UC6
  usecase "Load Plan" as UC7
  usecase "Render TSP on Map" as UC8
  usecase "Handle Invalid XML Error" as UC9
  usecase "Compute TSP" as UC10
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5
User --> UC6
User --> UC7
User --> UC8
User --> UC9

UC1 .> UC10 : <<include>>
UC2 .> UC10 : <<include>>
UC9 .> UC1 : <<extend>>
UC9 .> UC2 : <<extend>>

@enduml